version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=nick_redmine
      - MARIADB_DATABASE=nicholas_redmine
  redmine:
    image: docker.io/bitnami/redmine:5
    ports:
      # Open and use port 80 and 3000
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      # Database manager will be MariaDB
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=nick_redmine
      - REDMINE_DATABASE_NAME=nicholas_redmine
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
